# Generated by Django 4.2.2 on 2023-06-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_category_image_pattern"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image_pattern",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="media/category/"
            ),
        ),
    ]
