# Generated by Django 4.2.2 on 2023-06-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_category_image_pattern"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image_pattern",
            field=models.ImageField(blank=True, null=True, upload_to="category/"),
        ),
    ]
