# Generated by Django 4.2.2 on 2023-06-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_category_image_pattern"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="recipe",
            field=models.ManyToManyField(to="core.recipe"),
        ),
    ]
