# Generated by Django 4.2.2 on 2023-06-18 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_comment_parent_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="notice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.notice",
            ),
        ),
    ]
